name: stats
channels:
  - ejolly
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.29.3
  - pip=24.2
  - pymer4=0.8.2
  - python=3.11
  - r-matrix=1.6.3
  - pip:
      - ipython==8.22.1
      - jupyter==1.0.0
      - matplotlib==3.8.3
      - numpy==1.26.4
      - pandas==2.2.2
      - scipy==1.14.0

# After installation, to ensure the ipykernel is properly installed and set up:
# conda activate stats 
# python -m ipykernel install --user --name stats --display-name "Python (stats)"